---
- hosts: webservers
  become: true
  tasks:
  - name: installation of package
    when: ansible_os_family = "RedHat"
    yum: path={{item}} state=directory
    with_items:
    - curl
    - nginx
    - zip
    - vim
